# 项目基本信息
project_name: "my_project"
experiment_name: "default"

# 首次启动时间（自动生成）
first_start_time: null

# 基础目录
base_dir: "d:/logs"

# 日志配置
logger:
  # 全局日志级别
  global_console_level: "info"
  global_file_level: "debug"

  # 当前会话目录（自动生成）
  current_session_dir: null

  # 模块特定配置（可选）
  module_levels: {}
  #   module_name:
  #     console_level: "debug"
  #     file_level: "detail"

# 其他配置项...
# training:
#   batch_size: 32
#   learning_rate: 0.001
# ...